org.gradle.jvmargs=-Xmx3G
org.gradle.daemon=false
# The Minecraft version must agree with the Forge version to get a valid artifact
minecraft_version=1.20.1
# The Minecraft version range can use any release version of Minecraft as bounds.
minecraft_version_range=[1.20.1,1.21)
# The Forge version must agree with the Minecraft version to get a valid artifact
forge_version=47.4.0
# The Forge version range can use any version of Forge as bounds or match the loader version range
forge_version_range=[47,)
# The loader version range can only use the major version of Forge/FML as bounds
loader_version_range=[47,)
# The mapping channel/version to use for mappings.
mapping_channel=official
mapping_version=1.20.1
# The unique mod identifier for the mod. Must be lowercase in English locale. Must fit the regex [a-z][a-z0-9_]{1,63}
mod_id=multichat
# The human-readable display name for the mod.
mod_name=Multi-Chat Link
# The license of the mod. Review your options at https://choosealicense.com/. All Rights Reserved is the default.
mod_license=LGPL-3.0-only
# The mod version. See https://semver.org/
mod_version=1.0.1
# The group ID for the mod. Should match the base package used for the mod sources.
mod_group_id=de.taczbg
# The authors of the mod.
mod_authors=TACZ-BG
# The description of the mod.
mod_description=Bridges server chat with other servers and platforms through a Redis stream.
